version: '3'

services:  
  kibana:
    image: kibana:8.4.1
    container_name: kibana
    restart: 'unless-stopped'
    depends_on:
      - Elasticsearch
    environment:
     - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    networks:
      - api-note-elasticStack
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./kibana:/usr/share/kibana/data
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - '5601:5601'
    expose:
      - '5601'

networks:
  api-note-elasticStack:
    driver: bridge